name: Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta la acción diariamente a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: juan2929  # Tu nombre de usuario de GitHub
          output: dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg
      - name: Push to GitHub
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "jodofedosja@gmail.com"  # Tu correo
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake game"
          git push
